version: "3.9"

services:
  org_db_test:
    container_name: org_db_test
    image: postgres:15.2
    ports:
      - "5000:5432"
    environment:
      - POSTGRES_DB=org_test
      - POSTGRES_USER=org_test_user
      - POSTGRES_PASSWORD=org_test_pwd
    volumes:
      - ./.db_volumes/org_test_db:/var/lib/postgresql/data

  keycloak_db:
    container_name: keycloak_db
    image: postgres:15.2
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=kc_test
      - POSTGRES_USER=kc_test_user
      - POSTGRES_PASSWORD=kc_test_pwd
    volumes:
      - ./.db_volumes/kc_test:/var/lib/postgresql/data

  keycloak:
    container_name: 'keycloak'
    image: docker.io/bitnami/keycloak:latest
    environment:
      KEYCLOAK_DATABASE_VENDOR: POSTGRES
      KEYCLOAK_DATABASE_HOST: keycloak_db
      KEYCLOAK_DATABASE_PORT: 5432
      KEYCLOAK_DATABASE_NAME: kc_test
      KEYCLOAK_DATABASE_USER: kc_test_user
      KEYCLOAK_DATABASE_PASSWORD: kc_test_pwd
      KEYCLOAK_ADMIN_USER: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KEYCLOAK_HTTP_PORT: 8080
    ports:
      - '8090:8080'
    volumes:
      - ./.kc_imports:/opt/bitnami/keycloak/imports
    depends_on:
      keycloak_db:
        condition: service_started
