version: "3.9"

services:
  db_test:
    image: postgres
    ports:
      - "5431:5432"
    environment:
      - POSTGRES_DB=org_test
      - POSTGRES_USER=org_test_user
      - POSTGRES_PASSWORD=org_test_pwd

  db_uat:
    image: postgres
    volumes:
      - ./.db_volumes/org_uat_db:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=org_uat
      - POSTGRES_USER=org_uat_user
      - POSTGRES_PASSWORD=org_uat_pwd